# Generated by Django 3.2.7 on 2021-10-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Sala de Atención')),
                ('rango', models.CharField(max_length=100, verbose_name='Rango de edad')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la seccion')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre (s)')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('ingreso', models.DateField()),
                ('nacimiento', models.DateField()),
                ('curp', models.CharField(max_length=50, verbose_name='CURP')),
                ('nss', models.CharField(max_length=50, verbose_name='NSS')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número telefónico')),
                ('direccion', models.CharField(max_length=500, verbose_name='dirección')),
                ('sexo', models.CharField(max_length=500, verbose_name='Sexo')),
                ('type', models.CharField(choices=[('Empleado', 'Empleado'), ('Niño', 'Niño'), ('Padre', 'Padre')], max_length=50, verbose_name='Tipo de Registro')),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, verbose_name='Sexo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='Sala de atención')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion', verbose_name='Sección')),
            ],
        ),
    ]
