# Generated by Django 3.2.7 on 2021-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='foto',
            field=models.ImageField(null=True, upload_to='imgProducts', verbose_name='Foto'),
        ),
    ]
