# Generated by Django 3.2.7 on 2021-10-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='seccion',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Pedagogia', 'Pedagogia'), ('Fomento a la Salud', 'Fomento a la Salud'), ('Alimentación', 'Alimentación')], max_length=50, verbose_name='Area'),
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
