# Generated by Django 3.2.7 on 2021-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_registro_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='foto',
            field=models.ImageField(null=True, upload_to='imgProducts', verbose_name='Foto'),
        ),
    ]
