# Generated by Django 3.2.7 on 2021-10-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción del producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(verbose_name='Fecha y hora de ingreso')),
                ('area', models.CharField(choices=[('Administracion', 'Administracion'), ('Pedagogia', 'Pedagogia'), ('Fomento a la Salud', 'Fomento a la Salud'), ('Alimentación', 'Alimentación')], max_length=50, verbose_name='Area')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.compra', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacen',
            },
        ),
    ]
