# Generated by Django 3.2.7 on 2021-11-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='unidades',
            field=models.IntegerField(default='1', verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
