# Generated by Django 3.2.7 on 2021-11-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_almacen_unidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='unidades',
        ),
        migrations.AddField(
            model_name='almacen',
            name='unidad',
            field=models.CharField(default='unidad', max_length=100, verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
