# Generated by Django 3.2.7 on 2021-11-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20211101_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='unidad',
        ),
    ]
