# Generated by Django 3.2.7 on 2021-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_remove_almacen_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='type',
            field=models.CharField(choices=[{'Compra, Compra', 'Donación, Donación'}], default='', max_length=50, verbose_name='Tipo de adquisición'),
            preserve_default=False,
        ),
    ]
