# Generated by Django 3.2.7 on 2021-11-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_compra_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='type',
        ),
    ]
