# Generated by Django 3.2.7 on 2021-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='detalles',
            field=models.CharField(max_length=500, verbose_name='Detalles'),
        ),
    ]
