# Generated by Django 3.2.7 on 2021-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('type', models.CharField(choices=[('Administracion', 'Administracion'), ('Pedagogia', 'Pedagogia'), ('Fomento a la Salud', 'Fomento a la Salud'), ('Alimentación', 'Alimentación')], max_length=50, verbose_name='Tipo de Registro')),
                ('Detalles', models.CharField(choices=[('Administracion', 'Administracion'), ('Pedagogia', 'Pedagogia'), ('Fomento a la Salud', 'Fomento a la Salud'), ('Alimentación', 'Alimentación')], max_length=50, verbose_name='Tipo de Registro')),
                ('foto', models.ImageField(null=True, upload_to='imgProducts', verbose_name='Foto')),
            ],
        ),
    ]
