# Generated by Django 3.2.7 on 2021-11-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='Detalles',
        ),
        migrations.AddField(
            model_name='foto',
            name='detalles',
            field=models.CharField(default='detalles', max_length=500, verbose_name='Detalles'),
            preserve_default=False,
        ),
    ]
